package unblonded.packets;

import imgui.type.*;
import unblonded.packets.util.BlockColor;

import java.util.*;

public class cfg {
    public static boolean autoSprint = false;
    public static ImBoolean drawBlocks = new ImBoolean(false);
    public static ImBoolean drawBlockTracer = new ImBoolean(false);
    public static List<BlockColor> espBlockList = new ArrayList<>();
    public static ImBoolean forwardTunnel = new ImBoolean(false);
    public static ImBoolean autoCrystal = new ImBoolean(false);
    public static int[] crystalAttackTime = {20};
    public static int[] crystalPlaceTime = {20};
    public static ImBoolean cancelInteraction = new ImBoolean(false);
    public static ImBoolean autoAnchor = new ImBoolean(false);
    public static int[] autoAnchorDelay = {15};
    public static int[] autoAnchorHumanity = {3};
    public static ImLong oreSimSeed = new ImLong(0L);
    public static ImBoolean oreSim = new ImBoolean(false);
    public static ImBoolean oreSimDrawMode = new ImBoolean(false);
    public static int[] oreSimDistance = {3};
    public static float[] oreSimColor = {1.0f, 0.0f, 0.0f, 1.0f};
    public static ImBoolean autoTotem = new ImBoolean(false);
    public static int[] autoTotemDelay = {50};
    public static int[] autoTotemHumanity = {0};
    public static boolean triggerAutoSell = false;
    public static int[] autoSellDelay = {300};
    public static ImString autoSellPrice = new ImString(256);
    public static ImInt[] autoSellEndpoints = {new ImInt(0), new ImInt(8)};
    public static int filterMode = 0;
    public static ImBoolean chatFilter = new ImBoolean(false);
    public static ImString blockMsg = new ImString(512);
    public static ImBoolean storageScan = new ImBoolean(false);
    public static ImString storageScanSearch = new ImString(512);
    public static float[] storageScanColor = {1.0f, 0.0f, 0.0f, 1.0f};
    public static ImBoolean storageScanShowInGui = new ImBoolean(true);
    public static ImBoolean aimAssistToggle = new ImBoolean(false);
    public static boolean aimAssistVisibility = false;
    public static ImBoolean crystalSpam = new ImBoolean(false);
    public static int[] crystalSpamSearchRadius = {5};
    public static int[] crystalSpamBreakDelay = {10};
    public static ImBoolean selfCrystal = new ImBoolean(false);
    public static int[] selfCrystalDelay = {15};
    public static int[] selfCrystalHumanity = {3};
    public static boolean showMenu;
    public static boolean showAll;
    public static ImBoolean displayPlayers = new ImBoolean(false);
    public static ImBoolean advEsp = new ImBoolean(false);
    public static ImBoolean advEspDrawType = new ImBoolean(false);
    public static ImString blockName = new ImString(256);
    public static float[] blockColor = {1.f, 1.f, 1.f, 1.f};
    public static int[] espRadius = {32};
    public static int[] espBatchSize = {256};
    public static int[] espSearchTime = {1};
    public static ImBoolean checkPlayerAirSafety = new ImBoolean(false);
    public static ImBoolean isPlayerAirSafeShowStatus = new ImBoolean(true);
    public static ImBoolean freezePlayers = new ImBoolean(false);
    public static String tunnelBlockStatus;
    public static ImBoolean autoSell = new ImBoolean(false);
    public static ImBoolean autoDc = new ImBoolean(false);
    public static ImBoolean autoDcPrimed = new ImBoolean(false);
    public static ImFloat autoDcProximity = new ImFloat(5.0f);
    public static ImBoolean backgroundFx = new ImBoolean(true);
    public static String[] chatFilterItems = new String[]{ "Mute", "Contains", "Not Contain" };
    public static ImBoolean fontSizeOverride = new ImBoolean(false);;
    public static float[] fontSize = {1.5f};
    public static boolean storageScanShow;
    public static float[] aimAssistRange = {6.8f};
    public static float[] aimAssistFov = {128.2f};
    public static float[] aimAssistSmoothness = {1.0f};
    public static float[] aimAssistMinSpeed = {143.0f};
    public static float[] aimAssistMaxSpeed = {146.0f};
    public static ImBoolean aimAssistVisibilityCheck = new ImBoolean(true);
    public static int[] aimAssistUpdateRate = {1};
    public static ImBoolean nightFx = new ImBoolean(false);
    public static float[] nightFxSize = {20.f};
    public static ImBoolean nightFxCrosshairLines = new ImBoolean(false);
    public static ImBoolean showFpsChart = new ImBoolean(false);
    public static ImBoolean showFpsChartInGame = new ImBoolean(false);
    public static int[] fpsChartSampleRate = {5};

    public static ImBoolean autoCrystalCfg = new ImBoolean(false);
    public static ImBoolean advEspCfg = new ImBoolean(false);
    public static ImBoolean checkPlayerAirSafetyCfg = new ImBoolean(false);
    public static ImBoolean autoSellCfg = new ImBoolean(false);
    public static ImBoolean autoDcCfg = new ImBoolean(false);
    public static ImBoolean oreSimCfg = new ImBoolean(false);
    public static ImBoolean autoTotemCfg = new ImBoolean(false);
    public static ImBoolean chatFilterCfg = new ImBoolean(false);
    public static ImBoolean fontSizeCfg = new ImBoolean(false);
    public static ImBoolean aimAssistCfg = new ImBoolean(false);
    public static ImBoolean storageScanCfg = new ImBoolean(false);
    public static ImBoolean crystalSpamCfg = new ImBoolean(false);
    public static ImBoolean nightFxCfg = new ImBoolean(false);
    public static ImBoolean autoAnchorCfg = new ImBoolean(false);
    public static ImBoolean selfCrystalCfg = new ImBoolean(false);
    public static ImBoolean fpsChartCfg = new ImBoolean(false);

}
