package unblonded.packets;

import imgui.ImVec4;
import imgui.type.*;
import unblonded.packets.cheats.PlayerTracker;
import unblonded.packets.util.BlockColor;
import unblonded.packets.util.Color;

import java.util.*;

public class cfg {
    public static boolean autosprint = false;
    public static boolean drawBlocks = false;
    public static boolean drawBlockTracer = false;
    public static List<BlockColor> espBlockList = new ArrayList<>();
    public static int RADIUS = 128;
    public static int BATCH_SIZE = 200_000;
    public static int SEARCH_INTERVAL = 10_000;
    public static boolean checkPlayerSafety = false;
    public static ImBoolean forwardTunnel = new ImBoolean(false);
    public static ImBoolean autoCrystal = new ImBoolean(false);
    public static int[] crystalAttackTime = {20};
    public static int[] crystalPlaceTime = {20};
    public static ImBoolean cancelInteraction = new ImBoolean(false);
    public static ImBoolean autoAnchor = new ImBoolean(false);;
    public static int[] autoAnchorDelay = {15};
    public static int[] autoAnchorHumanity = {3};
    public static ImLong oreSimSeed = new ImLong(0L);
    public static ImBoolean oreSim = new ImBoolean(false);
    public static int oreSimDistance = 0;
    public static float[] oreSimColor = {1.0f, 0.0f, 0.0f, 1.0f};
    public static ImBoolean autoTotem = new ImBoolean(false);
    public static int[] autoTotemDelay = {50};
    public static int[] autoTotemHumanity = {0};
    public static boolean triggerAutoSell = false;
    public static int[] autoSellDelay = {300};
    public static ImString autoSellPrice = new ImString("0");
    public static ImInt[] autoSellEndpoints = {new ImInt(0), new ImInt(8)};
    public static boolean autoDcPrimed = false;
    public static float autoDcProximity = 30.0f;
    public static int filterMode = -1;
    public static ImBoolean chatFilter = new ImBoolean(false);
    public static ImString blockMsg = new ImString("");
    public static ImBoolean storageScan = new ImBoolean(false);
    public static ImString storageScanSearch = new ImString("");
    public static float[] storageScanColor = {1.0f, 0.0f, 0.0f, 1.0f};
    public static boolean storageScanShowInGui = false;
    public static ImBoolean aimAssistToggle = new ImBoolean(false);;
    public static boolean aimAssistVisibility = false;
    public static ImBoolean crystalSpam = new ImBoolean(false);;
    public static int[] crystalSpamSearchRadius = {5};
    public static int[] crystalSpamBreakDelay = {10};
    public static boolean drawCustomCrosshair = false;
    public static ImBoolean selfCrystal = new ImBoolean(false);;
    public static int[] selfCrystalDelay = {15};
    public static int[] selfCrystalHumanity = {3};
    public static boolean showMenu;
    public static boolean showAll;
    public static ImBoolean displayPlayers = new ImBoolean(false);
    public static ImBoolean advEsp = new ImBoolean(false);
    public static ImString blockName = new ImString("");
    public static float[] blockColor = {1.f, 1.f, 1.f, 1.f};
    public static int[] espRadius = {24};
    public static int[] espBatchSize = {256};
    public static int[] espSearchTime = {5};
    public static ImBoolean checkPlayerAirSafety = new ImBoolean(false);
    public static String isPlayerAirSafe;
    public static boolean isPlayerAirSafeShowStatus;
    public static ImBoolean freezePlayers = new ImBoolean(false);
    public static String tunnelBlockStatus;
    public static ImBoolean autoSell = new ImBoolean(false);
    public static ImBoolean autoDc = new ImBoolean(false);
    public static ImFloat autoDcCondition = new ImFloat(5.0f);
    public static ImBoolean backgroundFx = new ImBoolean(false);
    public static String[] chatFilterItems = new String[]{ "Mute", "Contains", "Not Contain" };
    public static ImBoolean fontSizeOverride = new ImBoolean(false);;
    public static float[] fontSize = {1.5f};
    public static boolean storageScanShow;
    public static float[] aimAssistRange = {6.8f};
    public static float[] aimAssistFov = {128.2f};
    public static float[] aimAssistSmoothness = {1.0f};
    public static float[] aimAssistMinSpeed = {143.0f};
    public static float[] aimAssistMaxSpeed = {146.0f};
    public static ImBoolean aimAssistVisibilityCheck = new ImBoolean(true);
    public static int[] aimAssistUpdateRate = {1};
    public static ImBoolean nightFx = new ImBoolean(false);
    public static float[] nightFxSize = {20.f};
    public static boolean nightFxCrosshairLines = true;

    public static ImBoolean autoCrystalcfg = new ImBoolean(false);
    public static ImBoolean advEspcfg = new ImBoolean(false);
    public static ImBoolean checkPlayerAirSafetycfg = new ImBoolean(false);
    public static ImBoolean autoSellcfg = new ImBoolean(false);
    public static ImBoolean autoDccfg = new ImBoolean(false);
    public static ImBoolean oreSimcfg = new ImBoolean(false);
    public static ImBoolean autoTotemcfg = new ImBoolean(false);
    public static ImBoolean chatFiltercfg = new ImBoolean(false);
    public static ImBoolean fontSizecfg = new ImBoolean(false);
    public static ImBoolean aimAssistcfg = new ImBoolean(false);
    public static ImBoolean storageScancfg = new ImBoolean(false);
    public static ImBoolean crystalSpamcfg = new ImBoolean(false);
    public static ImBoolean nightFxcfg = new ImBoolean(false);
    public static ImBoolean autoAnchorcfg = new ImBoolean(false);
    public static ImBoolean selfCrystalcfg = new ImBoolean(false);
}
